import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"],
weight: ["100", "200", "400", "700"],
display: "swap", });

export const metadata = {
  title: "Build Permit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
